"""
分子可视化模块

使用 py3Dmol 提供 Gaussian View 风格的分子结构可视化。
"""

import os
import json
import glob
from typing import Optional, List, Dict, Any, Tuple
from ase.db import connect
from ase import Atoms
import py3Dmol
import numpy as np

from emolagent.utils.logger import logger

# Element colors (CPK coloring scheme similar to Gaussian View)
ELEMENT_COLORS = {
    'H': '#FFFFFF',
    'C': '#909090',
    'N': '#3050F8',
    'O': '#FF0D0D',
    'F': '#90E050',
    'S': '#FFFF30',
    'P': '#FF8000',
    'Cl': '#1FF01F',
    'Br': '#A62929',
    'I': '#940094',
    'Li': '#8F40D4',
    'Na': '#AB5CF2',
    'K': '#8F40D4',
    'Mg': '#8AFF00',
    'Ca': '#3DFF00',
    'Fe': '#E06633',
    'Zn': '#7D80B0',
    'default': '#FF1493'
}

# Atom radii (in Angstroms, scaled for visualization)
ELEMENT_RADII = {
    'H': 0.31, 'C': 0.77, 'N': 0.71, 'O': 0.66, 'F': 0.57,
    'S': 1.05, 'P': 1.07, 'Cl': 1.02, 'Br': 1.20, 'I': 1.39,
    'Li': 1.34, 'Na': 1.54, 'K': 1.96, 'Mg': 1.30, 'Ca': 1.74,
    'Fe': 1.25, 'Zn': 1.22, 'default': 1.0
}


def atoms_to_xyz_string(atoms: Atoms, comment: str = "") -> str:
    """将 ASE Atoms 对象转换为 XYZ 格式字符串。"""
    n_atoms = len(atoms)
    lines = [str(n_atoms), comment]
    
    symbols = atoms.get_chemical_symbols()
    positions = atoms.get_positions()
    
    for sym, pos in zip(symbols, positions):
        lines.append(f"{sym:2s} {pos[0]:12.6f} {pos[1]:12.6f} {pos[2]:12.6f}")
    
    return "\n".join(lines)


def atomic_number_to_symbol(z: int) -> str:
    """将原子序数转换为元素符号。"""
    symbols = ['X', 'H', 'He', 'Li', 'Be', 'B', 'C', 'N', 'O', 'F', 'Ne',
               'Na', 'Mg', 'Al', 'Si', 'P', 'S', 'Cl', 'Ar', 'K', 'Ca',
               'Sc', 'Ti', 'V', 'Cr', 'Mn', 'Fe', 'Co', 'Ni', 'Cu', 'Zn',
               'Ga', 'Ge', 'As', 'Se', 'Br', 'Kr']
    if 0 <= z < len(symbols):
        return symbols[z]
    return 'X'


def create_gaussian_view_style_viewer(
    atoms: Atoms,
    width: int = 600,
    height: int = 500,
    style: str = "sphere+stick",
    background_color: str = "#1a1a2e",
    show_labels: bool = False,
    add_lighting: bool = True,
) -> str:
    """
    创建 Gaussian View 风格的 3D 分子查看器 HTML。
    
    Args:
        atoms: ASE Atoms 对象
        width: 查看器宽度（像素）
        height: 查看器高度（像素）
        style: 渲染样式 ("sphere", "stick", "sphere+stick")
        background_color: 背景颜色
        show_labels: 是否显示原子标签
        add_lighting: 是否添加增强光照效果
        
    Returns:
        包含交互式 3D 查看器的 HTML 字符串
    """
    xyz_str = atoms_to_xyz_string(atoms, "Generated by EMolAgent")
    
    viewer = py3Dmol.view(width=width, height=height)
    viewer.addModel(xyz_str, "xyz")
    
    if style == "sphere":
        viewer.setStyle({'sphere': {'colorscheme': 'Jmol', 'scale': 0.3}})
    elif style == "stick":
        viewer.setStyle({
            'stick': {'radius': 0.15, 'colorscheme': 'Jmol'},
        })
    else:
        viewer.setStyle({
            'sphere': {'colorscheme': 'Jmol', 'scale': 0.25},
            'stick': {'radius': 0.12, 'colorscheme': 'Jmol'}
        })
    
    viewer.setBackgroundColor(background_color)
    
    if show_labels:
        viewer.addPropertyLabels('elem', '', {'fontSize': 12, 'fontColor': 'white', 'showBackground': False})
    
    viewer.zoomTo()
    
    html = viewer._make_html()
    
    wrapper_html = f"""
    <div style="border: 2px solid #4a4a6a; border-radius: 8px; padding: 10px; background: #0d0d1a;">
        <div style="color: #aaa; font-size: 12px; margin-bottom: 5px; text-align: center;">
            🖱️ 左键拖动旋转 | 滚轮缩放 | 右键平移
        </div>
        {html}
        <div style="color: #888; font-size: 11px; margin-top: 5px; text-align: center;">
            原子数: {len(atoms)} | 化学式: {atoms.get_chemical_formula()}
        </div>
    </div>
    """
    
    return wrapper_html


def load_structure_from_db(db_path: str, index: int = 0) -> Optional[Atoms]:
    """从 ASE 数据库加载结构。"""
    if not os.path.exists(db_path):
        return None
    
    try:
        with connect(db_path) as db:
            if db.count() == 0:
                return None
            row = list(db.select())[index]
            return row.toatoms()
    except Exception as e:
        logger.error(f"Error loading structure: {e}")
        return None


def create_orbital_viewer(
    cube_path: str,
    width: int = 600,
    height: int = 500,
    iso_value: float = 0.02,
    orbital_type: str = "HOMO",
    background_color: str = "#1a1a2e",
) -> str:
    """
    创建分子轨道（cube 文件）可视化查看器。
    
    Args:
        cube_path: cube 文件路径
        width: 查看器宽度
        height: 查看器高度
        iso_value: 等值面数值
        orbital_type: 轨道类型 ("HOMO" 或 "LUMO")
        background_color: 背景颜色
        
    Returns:
        包含交互式 3D 轨道查看器的 HTML 字符串
    """
    if not os.path.exists(cube_path):
        return f"<p style='color: red;'>Cube 文件不存在: {cube_path}</p>"
    
    try:
        with open(cube_path, 'r') as f:
            cube_content = f.read()
        
        viewer = py3Dmol.view(width=width, height=height)
        
        if orbital_type.upper() == "HOMO":
            pos_color = "#1E90FF"
            neg_color = "#FF6347"
        else:
            pos_color = "#32CD32"
            neg_color = "#FFD700"
        
        viewer.addVolumetricData(cube_content, "cube", {
            'isoval': iso_value,
            'color': pos_color,
            'opacity': 0.75,
            'smoothness': 3
        })
        viewer.addVolumetricData(cube_content, "cube", {
            'isoval': -iso_value,
            'color': neg_color,
            'opacity': 0.75,
            'smoothness': 3
        })
        
        viewer.addModel(cube_content, "cube")
        viewer.setStyle({
            'sphere': {'colorscheme': 'Jmol', 'scale': 0.2},
            'stick': {'radius': 0.1, 'colorscheme': 'Jmol'}
        })
        
        viewer.setBackgroundColor(background_color)
        viewer.zoomTo()
        
        html = viewer._make_html()
        
        wrapper_html = f"""
        <div style="border: 2px solid #4a4a6a; border-radius: 8px; padding: 10px; background: #0d0d1a;">
            <div style="color: #aaa; font-size: 12px; margin-bottom: 5px; text-align: center;">
                🖱️ 左键拖动旋转 | 滚轮缩放 | 右键平移
            </div>
            {html}
            <div style="color: #888; font-size: 11px; margin-top: 5px; text-align: center;">
                {orbital_type} 轨道 | 等值面: ±{iso_value} &nbsp;
                <span style="color: {pos_color};">■</span> 正相位 &nbsp;
                <span style="color: {neg_color};">■</span> 负相位
            </div>
        </div>
        """
        
        return wrapper_html
        
    except Exception as e:
        return f"<p style='color: red;'>加载轨道可视化失败: {e}</p>"


def find_orbital_files(inference_dir: str) -> Dict[str, Optional[str]]:
    """在推断结果目录中查找 HOMO 和 LUMO cube 文件。"""
    result: Dict[str, Optional[str]] = {'homo': None, 'lumo': None}
    
    if not os.path.exists(inference_dir):
        return result
    
    search_patterns = [
        os.path.join(inference_dir, "results", "*", "homo.cube"),
        os.path.join(inference_dir, "results", "*", "lumo.cube"),
        os.path.join(inference_dir, "*", "homo.cube"),
        os.path.join(inference_dir, "*", "lumo.cube"),
        os.path.join(inference_dir, "homo.cube"),
        os.path.join(inference_dir, "lumo.cube"),
    ]
    
    for pattern in search_patterns:
        matches = glob.glob(pattern)
        for match in matches:
            basename = os.path.basename(match).lower()
            if 'homo' in basename and result['homo'] is None:
                result['homo'] = match
            elif 'lumo' in basename and result['lumo'] is None:
                result['lumo'] = match
    
    return result


def find_li_deformation_files(inference_dir: str) -> List[Dict[str, str]]:
    """
    在推断结果目录中查找 Li deformation surface PDB 文件。
    
    文件名格式: Li_infer_{id}_diff{isovalue}_surface.pdb
    
    Returns:
        包含 'path', 'id', 'isovalue' 键的字典列表
    """
    result: List[Dict[str, str]] = []
    
    if not os.path.exists(inference_dir):
        return result
    
    search_patterns = [
        os.path.join(inference_dir, "results", "*", "Li_*_surface.pdb"),
        os.path.join(inference_dir, "*", "Li_*_surface.pdb"),
        os.path.join(inference_dir, "Li_*_surface.pdb"),
    ]
    
    found_files = set()
    for pattern in search_patterns:
        matches = glob.glob(pattern)
        for match in matches:
            if match not in found_files:
                found_files.add(match)
                basename = os.path.basename(match)
                # 解析文件名: Li_infer_1_diff0p09_surface.pdb
                import re
                m = re.match(r'Li_(\w+)_(\d+)_diff(\w+)_surface\.pdb', basename)
                if m:
                    result.append({
                        'path': match,
                        'type': m.group(1),  # infer/pred/target
                        'id': m.group(2),
                        'isovalue': m.group(3).replace('p', '.'),  # 0p09 -> 0.09
                    })
    
    # 按 id 排序
    result.sort(key=lambda x: int(x.get('id', 0)))
    return result


def create_li_deformation_viewer(
    molecule_path: str,
    surface_pdb_path: str,
    width: int = 600,
    height: int = 500,
    surface_color: str = "#4A90D9",
    surface_opacity: float = 0.65,
    background_color: str = "#1a1a2e",
    isovalue: str = "0.09",
) -> str:
    """
    创建 Li deformation factor 可视化查看器。
    
    将点云 PDB 渲染为半透明表面，叠加在分子结构上，
    用于展示 Li 离子周围的电子变形分布。
    
    Args:
        molecule_path: 分子结构文件路径 (xyz 或 pdb)
        surface_pdb_path: Li deformation 点云 PDB 文件路径
        width: 查看器宽度
        height: 查看器高度
        surface_color: 表面颜色（默认冷蓝色）
        surface_opacity: 表面透明度
        background_color: 背景颜色
        isovalue: 等值面值（用于显示）
        
    Returns:
        包含交互式 3D 查看器的 HTML 字符串
    """
    # 检查文件是否存在
    if not os.path.exists(molecule_path):
        return f"<p style='color: red;'>分子结构文件不存在: {molecule_path}</p>"
    if not os.path.exists(surface_pdb_path):
        return f"<p style='color: red;'>表面点云文件不存在: {surface_pdb_path}</p>"
    
    try:
        # 1. 读取分子结构
        mol_ext = os.path.splitext(molecule_path)[1].lower()
        with open(molecule_path, 'r') as f:
            mol_content = f.read()
        
        # 确定分子文件格式
        if mol_ext == '.xyz':
            mol_format = 'xyz'
        elif mol_ext == '.pdb':
            mol_format = 'pdb'
        else:
            # 尝试自动检测
            mol_format = 'xyz' if mol_content.strip().split('\n')[0].strip().isdigit() else 'pdb'
        
        # 2. 读取表面点云 PDB
        with open(surface_pdb_path, 'r') as f:
            surface_content = f.read()
        
        # 3. 创建 py3Dmol 视图
        viewer = py3Dmol.view(width=width, height=height)
        
        # 4. 添加分子骨架 (Model 0)
        viewer.addModel(mol_content, mol_format)
        viewer.setStyle({'model': 0}, {
            'sphere': {'colorscheme': 'Jmol', 'scale': 0.25},
            'stick': {'radius': 0.12, 'colorscheme': 'Jmol'}
        })
        
        # 5. 添加点云并渲染为表面 (Model 1)
        viewer.addModel(surface_content, 'pdb')
        # 隐藏点云本身的原子显示
        viewer.setStyle({'model': 1}, {'sphere': {'scale': 0}})
        
        # 6. 为点云添加 VDW 表面（近似 QuickSurf 效果）
        # py3Dmol 的 addSurface 支持: VDW, MS (分子表面), SAS, SES
        viewer.addSurface(
            'VDW',
            {
                'opacity': surface_opacity,
                'color': surface_color,
            },
            {'model': 1}
        )
        
        # 7. 设置背景和视图
        viewer.setBackgroundColor(background_color)
        viewer.zoomTo()
        
        # 8. 生成 HTML
        html = viewer._make_html()
        
        wrapper_html = f"""
        <div style="border: 2px solid #4a4a6a; border-radius: 8px; padding: 10px; background: #0d0d1a;">
            <div style="color: #aaa; font-size: 12px; margin-bottom: 5px; text-align: center;">
                🖱️ 左键拖动旋转 | 滚轮缩放 | 右键平移
            </div>
            {html}
            <div style="color: #888; font-size: 11px; margin-top: 5px; text-align: center;">
                Li Deformation Factor | 等值面: {isovalue} &nbsp;
                <span style="display: inline-block; width: 12px; height: 12px; background: {surface_color}; border-radius: 2px; vertical-align: middle;"></span>
                <span style="color: {surface_color};"> 变形区域</span>
            </div>
        </div>
        """
        
        return wrapper_html
        
    except Exception as e:
        return f"<p style='color: red;'>加载 Li Deformation 可视化失败: {e}</p>"


def create_structure_preview_html(db_path: str, max_structures: int = 3) -> str:
    """为数据库中的结构创建 HTML 预览。"""
    if not os.path.exists(db_path):
        return "<p style='color: red;'>结构文件不存在</p>"
    
    try:
        with connect(db_path) as db:
            count = db.count()
            
            if count == 0:
                return "<p style='color: orange;'>数据库中没有结构</p>"
            
            html_parts = []
            html_parts.append(f"<div style='text-align: center; color: #888;'>共 {count} 个结构</div>")
            
            for i, row in enumerate(db.select()):
                if i >= max_structures:
                    html_parts.append(f"<p style='color: #888; text-align: center;'>... 还有 {count - max_structures} 个结构</p>")
                    break
                
                atoms = row.toatoms()
                name = row.get('name', f'Structure {i+1}')
                
                viewer_html = create_gaussian_view_style_viewer(
                    atoms, 
                    width=500, 
                    height=400,
                    style="sphere+stick"
                )
                
                html_parts.append(f"""
                <div style="margin: 15px 0; padding: 10px; border: 1px solid #333; border-radius: 8px;">
                    <h4 style="color: #fff; margin: 0 0 10px 0;">{name}</h4>
                    {viewer_html}
                </div>
                """)
            
            return "\n".join(html_parts)
            
    except Exception as e:
        return f"<p style='color: red;'>加载结构失败: {e}</p>"


def create_analysis_visualization_html(
    db_path: str,
    inference_dir: str,
    width: int = 600,
    height: int = 450
) -> Dict[str, Any]:
    """
    创建结构、HOMO、LUMO 的可视化 HTML。
    
    Returns:
        包含 'structure', 'homo', 'lumo' 键的字典
    """
    result: Dict[str, Any] = {
        'structure': None,
        'homo': None,
        'lumo': None,
        'structure_available': False,
        'homo_available': False,
        'lumo_available': False
    }
    
    if db_path and os.path.exists(db_path):
        try:
            atoms = load_structure_from_db(db_path)
            if atoms:
                result['structure'] = create_gaussian_view_style_viewer(
                    atoms, width=width, height=height, style="sphere+stick"
                )
                result['structure_available'] = True
        except Exception as e:
            result['structure'] = f"<p style='color: orange;'>结构加载失败: {e}</p>"
    
    orbital_files = find_orbital_files(inference_dir)
    
    if orbital_files['homo']:
        result['homo'] = create_orbital_viewer(
            orbital_files['homo'], 
            width=width, 
            height=height,
            iso_value=0.02,
            orbital_type="HOMO"
        )
        result['homo_available'] = True
    
    if orbital_files['lumo']:
        result['lumo'] = create_orbital_viewer(
            orbital_files['lumo'],
            width=width,
            height=height, 
            iso_value=0.02,
            orbital_type="LUMO"
        )
        result['lumo_available'] = True
    
    return result


def generate_high_quality_image(
    atoms: Atoms,
    output_path: str,
    width: int = 1200,
    height: int = 900,
    style: str = "sphere+stick"
) -> str:
    """生成高质量分子静态图像。"""
    html_content = create_gaussian_view_style_viewer(atoms, width, height, style)
    
    html_path = output_path.replace('.png', '.html')
    with open(html_path, 'w') as f:
        f.write(f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>Molecular Structure</title>
            <script src="https://3Dmol.org/build/3Dmol-min.js"></script>
        </head>
        <body style="margin: 0; padding: 0; background: #1a1a2e;">
            {html_content}
        </body>
        </html>
        """)
    
    return html_path
