"""
Gaussian View style molecular visualization using py3Dmol.
Provides high-quality rendering with lighting, interactive rotation, and zoom.
"""

import os
import json
from typing import Optional, List, Dict, Any
from ase.db import connect
from ase import Atoms
import py3Dmol

# Element colors (CPK coloring scheme similar to Gaussian View)
ELEMENT_COLORS = {
    'H': '#FFFFFF',   # White
    'C': '#909090',   # Gray
    'N': '#3050F8',   # Blue
    'O': '#FF0D0D',   # Red
    'F': '#90E050',   # Light Green
    'S': '#FFFF30',   # Yellow
    'P': '#FF8000',   # Orange
    'Cl': '#1FF01F',  # Green
    'Br': '#A62929',  # Dark Red
    'I': '#940094',   # Purple
    'Li': '#8F40D4',  # Purple
    'Na': '#AB5CF2',  # Light Purple
    'K': '#8F40D4',   # Purple
    'Mg': '#8AFF00',  # Bright Green
    'Ca': '#3DFF00',  # Green
    'Fe': '#E06633',  # Orange
    'Zn': '#7D80B0',  # Gray Blue
    'default': '#FF1493'  # Pink for unknown
}

# Atom radii (in Angstroms, scaled for visualization)
ELEMENT_RADII = {
    'H': 0.31, 'C': 0.77, 'N': 0.71, 'O': 0.66, 'F': 0.57,
    'S': 1.05, 'P': 1.07, 'Cl': 1.02, 'Br': 1.20, 'I': 1.39,
    'Li': 1.34, 'Na': 1.54, 'K': 1.96, 'Mg': 1.30, 'Ca': 1.74,
    'Fe': 1.25, 'Zn': 1.22, 'default': 1.0
}


def atoms_to_xyz_string(atoms: Atoms, comment: str = "") -> str:
    """Convert ASE Atoms object to XYZ format string."""
    n_atoms = len(atoms)
    lines = [str(n_atoms), comment]
    
    symbols = atoms.get_chemical_symbols()
    positions = atoms.get_positions()
    
    for sym, pos in zip(symbols, positions):
        lines.append(f"{sym:2s} {pos[0]:12.6f} {pos[1]:12.6f} {pos[2]:12.6f}")
    
    return "\n".join(lines)


def create_gaussian_view_style_viewer(
    atoms: Atoms,
    width: int = 600,
    height: int = 500,
    style: str = "sphere",  # "sphere", "stick", "sphere+stick"
    background_color: str = "#1a1a2e",
    show_labels: bool = False,
    add_lighting: bool = True,
) -> str:
    """
    Create a Gaussian View style 3D molecular viewer HTML.
    
    Args:
        atoms: ASE Atoms object
        width: Viewer width in pixels
        height: Viewer height in pixels
        style: Rendering style ("sphere", "stick", or "sphere+stick")
        background_color: Background color (dark for Gaussian View look)
        show_labels: Whether to show atom labels
        add_lighting: Whether to add enhanced lighting effects
        
    Returns:
        HTML string containing the interactive 3D viewer
    """
    xyz_str = atoms_to_xyz_string(atoms, "Generated by EMolAgent")
    
    viewer = py3Dmol.view(width=width, height=height)
    viewer.addModel(xyz_str, "xyz")
    
    # Apply Gaussian View-like styling
    if style == "sphere":
        # Space-filling model
        viewer.setStyle({'sphere': {'colorscheme': 'Jmol', 'scale': 0.3}})
    elif style == "stick":
        # Ball and stick model (Gaussian View default)
        viewer.setStyle({
            'stick': {'radius': 0.15, 'colorscheme': 'Jmol'},
        })
    else:  # sphere+stick (most similar to Gaussian View)
        viewer.setStyle({
            'sphere': {'colorscheme': 'Jmol', 'scale': 0.25},
            'stick': {'radius': 0.12, 'colorscheme': 'Jmol'}
        })
    
    # Set background (Gaussian View uses dark blue/black)
    viewer.setBackgroundColor(background_color)
    
    # Add labels if requested
    if show_labels:
        viewer.addPropertyLabels('elem', '', {'fontSize': 12, 'fontColor': 'white', 'showBackground': False})
    
    # Center and zoom
    viewer.zoomTo()
    
    # Get the HTML - py3Dmol will include proper lighting
    html = viewer._make_html()
    
    # Wrap in a container with controls info
    wrapper_html = f"""
    <div style="border: 2px solid #4a4a6a; border-radius: 8px; padding: 10px; background: #0d0d1a;">
        <div style="color: #aaa; font-size: 12px; margin-bottom: 5px; text-align: center;">
            🖱️ 左键拖动旋转 | 滚轮缩放 | 右键平移
        </div>
        {html}
        <div style="color: #888; font-size: 11px; margin-top: 5px; text-align: center;">
            原子数: {len(atoms)} | 化学式: {atoms.get_chemical_formula()}
        </div>
    </div>
    """
    
    return wrapper_html


def load_structure_from_db(db_path: str, index: int = 0) -> Optional[Atoms]:
    """Load a structure from ASE database."""
    if not os.path.exists(db_path):
        return None
    
    try:
        with connect(db_path) as db:
            if db.count() == 0:
                return None
            row = list(db.select())[index]
            return row.toatoms()
    except Exception as e:
        print(f"Error loading structure: {e}")
        return None


def create_structure_preview_html(db_path: str, max_structures: int = 3) -> str:
    """
    Create HTML preview for structures in a database.
    Shows up to max_structures in a gallery view.
    """
    if not os.path.exists(db_path):
        return "<p style='color: red;'>结构文件不存在</p>"
    
    try:
        with connect(db_path) as db:
            count = db.count()
            
            if count == 0:
                return "<p style='color: orange;'>数据库中没有结构</p>"
            
            html_parts = []
            html_parts.append(f"<div style='text-align: center; color: #888;'>共 {count} 个结构</div>")
            
            for i, row in enumerate(db.select()):
                if i >= max_structures:
                    html_parts.append(f"<p style='color: #888; text-align: center;'>... 还有 {count - max_structures} 个结构</p>")
                    break
                
                atoms = row.toatoms()
                name = row.get('name', f'Structure {i+1}')
                
                viewer_html = create_gaussian_view_style_viewer(
                    atoms, 
                    width=500, 
                    height=400,
                    style="sphere+stick"
                )
                
                html_parts.append(f"""
                <div style="margin: 15px 0; padding: 10px; border: 1px solid #333; border-radius: 8px;">
                    <h4 style="color: #fff; margin: 0 0 10px 0;">{name}</h4>
                    {viewer_html}
                </div>
                """)
            
            return "\n".join(html_parts)
            
    except Exception as e:
        return f"<p style='color: red;'>加载结构失败: {e}</p>"


def generate_high_quality_image(
    atoms: Atoms,
    output_path: str,
    width: int = 1200,
    height: int = 900,
    style: str = "sphere+stick"
) -> str:
    """
    Generate a high-quality static image of the molecule.
    Note: This requires additional libraries like ASE's visualization or matplotlib.
    
    For now, returns the path to an HTML file that can be screenshotted.
    """
    html_content = create_gaussian_view_style_viewer(atoms, width, height, style)
    
    html_path = output_path.replace('.png', '.html')
    with open(html_path, 'w') as f:
        f.write(f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>Molecular Structure</title>
            <script src="https://3Dmol.org/build/3Dmol-min.js"></script>
        </head>
        <body style="margin: 0; padding: 0; background: #1a1a2e;">
            {html_content}
        </body>
        </html>
        """)
    
    return html_path