"""
Gaussian View style molecular visualization using py3Dmol.
Provides high-quality rendering with lighting, interactive rotation, and zoom.
"""

import os
import json
import glob
from typing import Optional, List, Dict, Any, Tuple
from ase.db import connect
from ase import Atoms
import py3Dmol
import numpy as np

# Element colors (CPK coloring scheme similar to Gaussian View)
ELEMENT_COLORS = {
    'H': '#FFFFFF',   # White
    'C': '#909090',   # Gray
    'N': '#3050F8',   # Blue
    'O': '#FF0D0D',   # Red
    'F': '#90E050',   # Light Green
    'S': '#FFFF30',   # Yellow
    'P': '#FF8000',   # Orange
    'Cl': '#1FF01F',  # Green
    'Br': '#A62929',  # Dark Red
    'I': '#940094',   # Purple
    'Li': '#8F40D4',  # Purple
    'Na': '#AB5CF2',  # Light Purple
    'K': '#8F40D4',   # Purple
    'Mg': '#8AFF00',  # Bright Green
    'Ca': '#3DFF00',  # Green
    'Fe': '#E06633',  # Orange
    'Zn': '#7D80B0',  # Gray Blue
    'default': '#FF1493'  # Pink for unknown
}

# Atom radii (in Angstroms, scaled for visualization)
ELEMENT_RADII = {
    'H': 0.31, 'C': 0.77, 'N': 0.71, 'O': 0.66, 'F': 0.57,
    'S': 1.05, 'P': 1.07, 'Cl': 1.02, 'Br': 1.20, 'I': 1.39,
    'Li': 1.34, 'Na': 1.54, 'K': 1.96, 'Mg': 1.30, 'Ca': 1.74,
    'Fe': 1.25, 'Zn': 1.22, 'default': 1.0
}


def atoms_to_xyz_string(atoms: Atoms, comment: str = "") -> str:
    """Convert ASE Atoms object to XYZ format string."""
    n_atoms = len(atoms)
    lines = [str(n_atoms), comment]
    
    symbols = atoms.get_chemical_symbols()
    positions = atoms.get_positions()
    
    for sym, pos in zip(symbols, positions):
        lines.append(f"{sym:2s} {pos[0]:12.6f} {pos[1]:12.6f} {pos[2]:12.6f}")
    
    return "\n".join(lines)


def atomic_number_to_symbol(z: int) -> str:
    """Convert atomic number to element symbol."""
    symbols = ['X', 'H', 'He', 'Li', 'Be', 'B', 'C', 'N', 'O', 'F', 'Ne',
               'Na', 'Mg', 'Al', 'Si', 'P', 'S', 'Cl', 'Ar', 'K', 'Ca',
               'Sc', 'Ti', 'V', 'Cr', 'Mn', 'Fe', 'Co', 'Ni', 'Cu', 'Zn',
               'Ga', 'Ge', 'As', 'Se', 'Br', 'Kr']
    if 0 <= z < len(symbols):
        return symbols[z]
    return 'X'


def create_gaussian_view_style_viewer(
    atoms: Atoms,
    width: int = 600,
    height: int = 500,
    style: str = "sphere",  # "sphere", "stick", "sphere+stick"
    background_color: str = "#1a1a2e",
    show_labels: bool = False,
    add_lighting: bool = True,
) -> str:
    """
    Create a Gaussian View style 3D molecular viewer HTML.
    
    Args:
        atoms: ASE Atoms object
        width: Viewer width in pixels
        height: Viewer height in pixels
        style: Rendering style ("sphere", "stick", or "sphere+stick")
        background_color: Background color (dark for Gaussian View look)
        show_labels: Whether to show atom labels
        add_lighting: Whether to add enhanced lighting effects
        
    Returns:
        HTML string containing the interactive 3D viewer
    """
    xyz_str = atoms_to_xyz_string(atoms, "Generated by EMolAgent")
    
    viewer = py3Dmol.view(width=width, height=height)
    viewer.addModel(xyz_str, "xyz")
    
    # Apply Gaussian View-like styling
    if style == "sphere":
        # Space-filling model
        viewer.setStyle({'sphere': {'colorscheme': 'Jmol', 'scale': 0.3}})
    elif style == "stick":
        # Ball and stick model (Gaussian View default)
        viewer.setStyle({
            'stick': {'radius': 0.15, 'colorscheme': 'Jmol'},
        })
    else:  # sphere+stick (most similar to Gaussian View)
        viewer.setStyle({
            'sphere': {'colorscheme': 'Jmol', 'scale': 0.25},
            'stick': {'radius': 0.12, 'colorscheme': 'Jmol'}
        })
    
    # Set background (Gaussian View uses dark blue/black)
    viewer.setBackgroundColor(background_color)
    
    # Add labels if requested
    if show_labels:
        viewer.addPropertyLabels('elem', '', {'fontSize': 12, 'fontColor': 'white', 'showBackground': False})
    
    # Center and zoom
    viewer.zoomTo()
    
    # Get the HTML - py3Dmol will include proper lighting
    html = viewer._make_html()
    
    # Wrap in a container with controls info
    wrapper_html = f"""
    <div style="border: 2px solid #4a4a6a; border-radius: 8px; padding: 10px; background: #0d0d1a;">
        <div style="color: #aaa; font-size: 12px; margin-bottom: 5px; text-align: center;">
            🖱️ 左键拖动旋转 | 滚轮缩放 | 右键平移
        </div>
        {html}
        <div style="color: #888; font-size: 11px; margin-top: 5px; text-align: center;">
            原子数: {len(atoms)} | 化学式: {atoms.get_chemical_formula()}
        </div>
    </div>
    """
    
    return wrapper_html


def load_structure_from_db(db_path: str, index: int = 0) -> Optional[Atoms]:
    """Load a structure from ASE database."""
    if not os.path.exists(db_path):
        return None
    
    try:
        with connect(db_path) as db:
            if db.count() == 0:
                return None
            row = list(db.select())[index]
            return row.toatoms()
    except Exception as e:
        print(f"Error loading structure: {e}")
        return None


def create_orbital_viewer(
    cube_path: str,
    width: int = 600,
    height: int = 500,
    iso_value: float = 0.02,
    orbital_type: str = "HOMO",
    background_color: str = "#1a1a2e",
) -> str:
    """
    Create a 3D viewer for molecular orbital (cube file) visualization.
    
    Args:
        cube_path: Path to the .cube file
        width: Viewer width in pixels
        height: Viewer height in pixels  
        iso_value: Isosurface value for orbital visualization
        orbital_type: Type of orbital ("HOMO" or "LUMO") for coloring
        background_color: Background color
        
    Returns:
        HTML string containing the interactive 3D orbital viewer
    """
    if not os.path.exists(cube_path):
        return f"<p style='color: red;'>Cube 文件不存在: {cube_path}</p>"
    
    try:
        # Read cube file content
        with open(cube_path, 'r') as f:
            cube_content = f.read()
        
        viewer = py3Dmol.view(width=width, height=height)
        
        # Add the volumetric data with isosurface
        # Use different colors for HOMO and LUMO
        if orbital_type.upper() == "HOMO":
            pos_color = "#1E90FF"  # Dodger Blue
            neg_color = "#FF6347"  # Tomato Red
        else:  # LUMO
            pos_color = "#32CD32"  # Lime Green  
            neg_color = "#FFD700"  # Gold
        
        # Add positive lobe
        viewer.addVolumetricData(cube_content, "cube", {
            'isoval': iso_value,
            'color': pos_color,
            'opacity': 0.75,
            'smoothness': 3
        })
        # Add negative lobe
        viewer.addVolumetricData(cube_content, "cube", {
            'isoval': -iso_value,
            'color': neg_color,
            'opacity': 0.75,
            'smoothness': 3
        })
        
        # Also show the molecular structure
        viewer.addModel(cube_content, "cube")
        viewer.setStyle({
            'sphere': {'colorscheme': 'Jmol', 'scale': 0.2},
            'stick': {'radius': 0.1, 'colorscheme': 'Jmol'}
        })
        
        viewer.setBackgroundColor(background_color)
        viewer.zoomTo()
        
        html = viewer._make_html()
        
        # Wrap with controls info
        wrapper_html = f"""
        <div style="border: 2px solid #4a4a6a; border-radius: 8px; padding: 10px; background: #0d0d1a;">
            <div style="color: #aaa; font-size: 12px; margin-bottom: 5px; text-align: center;">
                🖱️ 左键拖动旋转 | 滚轮缩放 | 右键平移
            </div>
            {html}
            <div style="color: #888; font-size: 11px; margin-top: 5px; text-align: center;">
                {orbital_type} 轨道 | 等值面: ±{iso_value} &nbsp;
                <span style="color: {pos_color};">■</span> 正相位 &nbsp;
                <span style="color: {neg_color};">■</span> 负相位
            </div>
        </div>
        """
        
        return wrapper_html
        
    except Exception as e:
        return f"<p style='color: red;'>加载轨道可视化失败: {e}</p>"


def find_orbital_files(inference_dir: str) -> Dict[str, Optional[str]]:
    """
    Find HOMO and LUMO cube files in the inference results directory.
    
    Args:
        inference_dir: Path to inference results directory
        
    Returns:
        Dictionary with 'homo' and 'lumo' keys pointing to file paths
    """
    result: Dict[str, Optional[str]] = {'homo': None, 'lumo': None}
    
    if not os.path.exists(inference_dir):
        return result
    
    # Search in various possible locations
    search_patterns = [
        os.path.join(inference_dir, "results", "*", "homo.cube"),
        os.path.join(inference_dir, "results", "*", "lumo.cube"),
        os.path.join(inference_dir, "*", "homo.cube"),
        os.path.join(inference_dir, "*", "lumo.cube"),
        os.path.join(inference_dir, "homo.cube"),
        os.path.join(inference_dir, "lumo.cube"),
    ]
    
    for pattern in search_patterns:
        matches = glob.glob(pattern)
        for match in matches:
            basename = os.path.basename(match).lower()
            if 'homo' in basename and result['homo'] is None:
                result['homo'] = match
            elif 'lumo' in basename and result['lumo'] is None:
                result['lumo'] = match
    
    return result


def create_structure_preview_html(db_path: str, max_structures: int = 3) -> str:
    """
    Create HTML preview for structures in a database.
    Shows up to max_structures in a gallery view.
    """
    if not os.path.exists(db_path):
        return "<p style='color: red;'>结构文件不存在</p>"
    
    try:
        with connect(db_path) as db:
            count = db.count()
            
            if count == 0:
                return "<p style='color: orange;'>数据库中没有结构</p>"
            
            html_parts = []
            html_parts.append(f"<div style='text-align: center; color: #888;'>共 {count} 个结构</div>")
            
            for i, row in enumerate(db.select()):
                if i >= max_structures:
                    html_parts.append(f"<p style='color: #888; text-align: center;'>... 还有 {count - max_structures} 个结构</p>")
                    break
                
                atoms = row.toatoms()
                name = row.get('name', f'Structure {i+1}')
                
                viewer_html = create_gaussian_view_style_viewer(
                    atoms, 
                    width=500, 
                    height=400,
                    style="sphere+stick"
                )
                
                html_parts.append(f"""
                <div style="margin: 15px 0; padding: 10px; border: 1px solid #333; border-radius: 8px;">
                    <h4 style="color: #fff; margin: 0 0 10px 0;">{name}</h4>
                    {viewer_html}
                </div>
                """)
            
            return "\n".join(html_parts)
            
    except Exception as e:
        return f"<p style='color: red;'>加载结构失败: {e}</p>"


def create_analysis_visualization_html(
    db_path: str,
    inference_dir: str,
    width: int = 600,
    height: int = 450
) -> Dict[str, Any]:
    """
    Create visualization HTML for structure, HOMO, and LUMO.
    
    Returns:
        Dictionary with 'structure', 'homo', 'lumo' keys containing HTML strings
        and 'xxx_available' boolean flags
    """
    result: Dict[str, Any] = {
        'structure': None,
        'homo': None,
        'lumo': None,
        'structure_available': False,
        'homo_available': False,
        'lumo_available': False
    }
    
    # Structure visualization
    if db_path and os.path.exists(db_path):
        try:
            atoms = load_structure_from_db(db_path)
            if atoms:
                result['structure'] = create_gaussian_view_style_viewer(
                    atoms, width=width, height=height, style="sphere+stick"
                )
                result['structure_available'] = True
        except Exception as e:
            result['structure'] = f"<p style='color: orange;'>结构加载失败: {e}</p>"
    
    # Find and visualize orbitals
    orbital_files = find_orbital_files(inference_dir)
    
    if orbital_files['homo']:
        result['homo'] = create_orbital_viewer(
            orbital_files['homo'], 
            width=width, 
            height=height,
            iso_value=0.02,
            orbital_type="HOMO"
        )
        result['homo_available'] = True
    
    if orbital_files['lumo']:
        result['lumo'] = create_orbital_viewer(
            orbital_files['lumo'],
            width=width,
            height=height, 
            iso_value=0.02,
            orbital_type="LUMO"
        )
        result['lumo_available'] = True
    
    return result


def generate_high_quality_image(
    atoms: Atoms,
    output_path: str,
    width: int = 1200,
    height: int = 900,
    style: str = "sphere+stick"
) -> str:
    """
    Generate a high-quality static image of the molecule.
    Note: This requires additional libraries like ASE's visualization or matplotlib.
    
    For now, returns the path to an HTML file that can be screenshotted.
    """
    html_content = create_gaussian_view_style_viewer(atoms, width, height, style)
    
    html_path = output_path.replace('.png', '.html')
    with open(html_path, 'w') as f:
        f.write(f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>Molecular Structure</title>
            <script src="https://3Dmol.org/build/3Dmol-min.js"></script>
        </head>
        <body style="margin: 0; padding: 0; background: #1a1a2e;">
            {html_content}
        </body>
        </html>
        """)
    
    return html_path